var hello = "hello ";
var world = "world!";
var hw = hello + world;
print hw;
hello = "bon jour ";
world = "planet!";
print hello + world;

var memo = Table();
fn fib(n) {
  if (n < 2) return n;
  var m = memo.get(n);
  if (m != null) {
    return m;
  }
  var a = fib(n - 1) + fib(n - 2);
  memo.put(n, a);
  return a;
}

var start = clock_milli();
print fib(100);
print (clock_milli() - start)/1000;