var list = [1,2,3];

list.append("hello");
list.append("another items");
list[1] = null;

var tab = Table();

tab.put("a", "hello");


var new_list = list.slice(1,3);

for (var i = 0; i < new_list.length(); i = i+1) {
  print new_list[i];
}

print "hello " + list[0] + " how are you doing?";

var hw = "hello world!";
print "'" + hw + "'";
assert(hw, "hello world!");

var slice = hw.slice(6,hw.length());
print slice.length();

var t = Table();

t.put("sam", 36);
t.put("Charlotte", 32);

print "Sam: " + t.get("sam");

var keys = t.keys();

for (var i = 0; i < keys.length(); i = i + 1) {
  print keys[i];
}

class Animal {
  name = "Animal";
  status = "alive";

  fn describe() {
    print "I am an animal";
  }

  fn breath() {
    print "inhale... exhale...";
  }
}

class Dog : Animal {
  name = "Dog";
  fn init() {
    print self.name + " is born.";
  }
  fn describe() {
    super.describe();
    print "I am a dog";
  }
}

class Labrador : Dog {
  name = "Labrador";
  fn describe() {
    super.describe();
    print "I am a Labrador";
  }
}

class ZombieDog : Dog {
  name = "Zombie Dog";
  status = "undead";
  fn describe() {
    super.describe();
    print "I am a zombie dog";
  }

  fn breath() {
    print "rattle... wheeze...";
  }
}

var dog = Dog();

dog.describe();
dog.breath();

var lab = Labrador();

lab.describe();
lab.breath();
var animal = Animal();
var zomdog = ZombieDog();
zomdog.breath();
zomdog.describe();
print "Animal status: " + animal.status;
print "Labrador status: " + lab.status;
print "Zombie Dog status: " + zomdog.status;

class Animal2 {
  name = "Animal";
  status = "alive";

  fn describe() {
    print "I am an animal";
  }

  fn breath() {
    print "inhale... exhale...";
  }
}

class Dog2 : Animal2 {
  name = "Dog";
  fn init() {
    print self.name + " is born.";
  }
  fn describe() {
    super.describe();
    print "I am a dog";
  }
}

class Labrador2 : Dog2 {
  name = "Labrador";
  fn describe() {
    super.describe();
    print "I am a Labrador";
  }
}

class ZombieDog2 : Dog2 {
  name = "Zombie Dog";
  status = "undead";
  fn describe() {
    super.describe();
    print "I am a zombie dog";
  }

  fn breath() {
    print "rattle... wheeze...";
  }
}

dog = Dog2();

dog.describe();
dog.breath();

var lab = Labrador2();

lab.describe();
lab.breath();
var animal2 = Animal2();
var zomdog2 = ZombieDog2();
zomdog2.breath();
zomdog2.describe();
print "Animal status: " + animal.status;
print "Labrador status: " + lab.status;
print "Zombie Dog status: " + zomdog2.status;
print tab.get("a");